# Generated by Django 5.1.1 on 2024-09-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=500)),
                ('designation', models.CharField(max_length=100)),
                ('sort_discription', models.CharField(max_length=500)),
                ('birth', models.DateField()),
                ('website_link', models.URLField(max_length=1000)),
                ('phone', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=10)),
                ('degree', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
