# Generated by Django 5.1.1 on 2024-09-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_social_alter_about_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='y_link',
            new_name='i_link',
        ),
        migrations.AlterField(
            model_name='social',
            name='t_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
