# Generated by Django 5.1.1 on 2024-09-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_y_link_social_i_link_alter_social_t_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='fb_link',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='social',
            name='i_link',
        ),
        migrations.RemoveField(
            model_name='social',
            name='l_link',
        ),
        migrations.RemoveField(
            model_name='social',
            name='t_link',
        ),
        migrations.AddField(
            model_name='social',
            name='social_icon',
            field=models.CharField(default='empty', max_length=100),
        ),
    ]
